### ISSUE TITLE
不能生成BOM

### ISSUE THREAD

**Issue by zhtrx** [xtoolbox/kicad_tools#8]
Start generate BOM list
Start generate position file
Error:
Traceback (most recent call last):
  File "C:\Users\sujia\AppData\Roaming\kicad\scripting\plugins/kicad_tools/mf_tool.py", line 705, in Onclick
    GenMFDoc(needGenBOM = self.chkBOM.GetValue(), needGenPos = self.chkPos.GetValue(), logger = lambda *args: self.log(*args) )
  File "C:\Users\sujia\AppData\Roaming\kicad\scripting\plugins/kicad_tools/mf_tool.py", line 531, in GenMFDoc
    bound = GetBoardBound(brd)
  File "C:\Users\sujia\AppData\Roaming\kicad\scripting\plugins/kicad_tools/mf_tool.py", line 113, in GetBoardBound
    w = d.GetWidth()
AttributeError: 'NoneType' object has no attribute 'GetWidth'

**Comment by yuan545** [comment]
遇到同样的问题：
Start generate BOM list
Start generate position file
Error:
Traceback (most recent call last):
  File "C:\Users\yang\AppData\Roaming\kicad\scripting\plugins/kicad_tools/mf_tool.py", line 705, in Onclick
    GenMFDoc(needGenBOM = self.chkBOM.GetValue(), needGenPos = self.chkPos.GetValue(), logger = lambda *args: self.log(*args) )
  File "C:\Users\yang\AppData\Roaming\kicad\scripting\plugins/kicad_tools/mf_tool.py", line 531, in GenMFDoc
    bound = GetBoardBound(brd)
  File "C:\Users\yang\AppData\Roaming\kicad\scripting\plugins/kicad_tools/mf_tool.py", line 124, in GetBoardBound
    rect.SetX(rect.GetX() + w/2)
AttributeError: 'NoneType' object has no attribute 'SetX'

**Comment by taotieren** [comment]
[KiCad-CN 用户也反馈同样问题](https://gitee.com/KiCAD-CN/kicad-cn-forum/issues/I1F6LU#note_2454739) 已解决
可供参考
